services:
  mysql-database:
    image: mysql:8.0.40
    container_name: meu-projeto-bd2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234' 
      MYSQL_DATABASE: 'bd2'    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-data: